server:
  port: 8453
  address: 0.0.0.0
  forward-headers-strategy: native

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mindflow_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
  
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:mongo}:${MONGO_PORT:27017}/mindflow_db?authSource=${MONGO_AUTH_SOURCE:admin}
      database: mindflow_db

  neo4j:
    uri: bolt://neo4j:7687

    authentication:
      username: ${NEO4J_USER:neo4j}
      password: ${NEO4J_PASSWORD:REDACTEDREDACTED}
    database: mindmap

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_REDIRECT_BASE_URL}/api/auth/oauth2/callback/google
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code

            #      github:
            #      client-id: ${GITHUB_CLIENT_ID}
            #      client-secret: ${GITHUB_CLIENT_SECRET}
            #      scope: user:email, read:user

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${OAUTH2_REDIRECT_BASE_URL}/api/auth/oauth2/callback/kakao
            scope: profile_nickname, profile_image, account_email
            client-name: Mindflow

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

python:
  server:
    url: http://flask:5001