server:
    port: 8453
    address: 0.0.0.0

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mindflow_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            username: REDACTED
            password: REDACTED

    data:
        mongodb:
           uri: mongodb://localhost:27017/mindflow_db

    neo4j:
        uri: bolt://neo4j:7687
        authentication:
            username: neo4j
            password: REDACTEDREDACTED

python:
    server:
       url: http://localhost:5000
