server:
  port: 8453
  address: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mindflow_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: REDACTED
      password: REDACTED

  data:
    mongodb:
      uri: mongodb://REDACTED:REDACTED@localhost:27018/mindflow_db?authSource=admin

  neo4j:
    uri: bolt://localhost:7688
    authentication:
      username: neo4j
      password: REDACTEDREDACTED

python:
  server:
    url: http://127.0.0.1:5001